name: Deploy Website

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write
    deployments: write

# Prevent concurrent executions and cancel builds in progress except on main
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        environment:
            name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            # Extract Node.js and pnpm versions from package.json
            - name: Extract versions from package.json
              id: versions
              run: |
                  NODE_VERSION=$(node -p "require('./package.json').engines?.node || '22'")
                  echo "node-version=$NODE_VERSION" >> $GITHUB_OUTPUT

            # Setup pnpm
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            # Get pnpm store directory for caching
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            # Cache Node.js
            - name: Cache pnpm in Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ steps.versions.outputs.node-version }}
                  cache: 'pnpm'
                  cache-dependency-path: '**/pnpm-lock.yaml'

            # Cache Next.js build
            - name: Cache Next.js build
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # Build Project Artifacts
            - name: Build Project
              run: pnpm build

            # Check if running in GitHub Actions or locally with act
            - name: Check if running in GitHub Actions
              id: check_github_actions
              run: |
                  if [ "$GITHUB_ACTIONS" = "true" ] && [ -n "$GITHUB_HEAD_REF" ]; then
                    echo "is_github_actions=true" >> $GITHUB_OUTPUT
                  else
                    echo "is_github_actions=false" >> $GITHUB_OUTPUT
                  fi

            # Deploy to Vercel using amondnet/vercel-action (only in GitHub Actions, not locally)
            - name: Deploy to Vercel
              if: steps.check_github_actions.outputs.is_github_actions == 'true'
              uses: amondnet/vercel-action@v25
              id: deploy
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}

            # Comment on PR with deployment URL (only in GitHub Actions, not locally)
            - name: Comment on PR
              if: github.event_name == 'pull_request' && steps.check_github_actions.outputs.is_github_actions == 'true'
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const issue_number = context.issue.number;
                      const deploymentUrl = '${{ steps.deploy.outputs.preview-url }}';

                      github.rest.issues.createComment({
                        issue_number: issue_number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `🚀 Deployment Preview: [Visit Preview](${deploymentUrl})`
                      });
