name: Local Test

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'pnpm'

            # Cache Next.js build
            - name: Cache Next.js build
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Project
              run: pnpm build
              env:
                  NEXT_PUBLIC_CLIENT_PRIVATE_KEY: '0x555357496d024bbc995c6304213637c4f69fe0bbd044ea103b61957962571699'
                  NEXT_PUBLIC_CLIENT_SWA: '0x6abff94c633ab6F6FE5422d7494D517970105719'
